//go:build ignore

// Generate functional_zones_data.go from data/functional_zones_national.json
//
//go:generate go run gen_functional_zones.go

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"
)

type zoneEntry struct {
	ZoneID   string   `json:"zone_id"`
	Type     string   `json:"type"`
	Name     string   `json:"name"`
	District string   `json:"district"`
	Aliases  []string `json:"aliases"`
}

type zoneFile struct {
	Zones []zoneEntry `json:"zones"`
}

func main() {
	dir := "."
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	inPath := filepath.Join(dir, "data", "functional_zones_national.json")
	outPath := filepath.Join(dir, "functional_zones_data.go")

	raw, err := os.ReadFile(inPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", inPath, err)
		os.Exit(1)
	}
	var zf zoneFile
	if err := json.Unmarshal(raw, &zf); err != nil {
		fmt.Fprintf(os.Stderr, "parse json: %v\n", err)
		os.Exit(1)
	}

	aliasToDistrict := make(map[string]string)
	for _, z := range zf.Zones {
		if z.District == "" {
			fmt.Fprintf(os.Stderr, "empty district for zone %q\n", z.Name)
			os.Exit(1)
		}
		for _, a := range z.Aliases {
			a = strings.TrimSpace(a)
			if a == "" {
				continue
			}
            if utf8.RuneCountInString(a) < 4 {
				// 专名简称如「中关村」「松山湖」由 extra_aliases 在 JSON 中显式维护且长度≥4
				fmt.Fprintf(os.Stderr, "alias too short (skip): %q\n", a)
				continue
			}
			if prev, ok := aliasToDistrict[a]; ok && prev != z.District {
				fmt.Fprintf(os.Stderr, "duplicate alias %q: %q vs %q\n", a, prev, z.District)
				os.Exit(1)
			}
			aliasToDistrict[a] = z.District
		}
	}

	keys := make([]string, 0, len(aliasToDistrict))
	for k := range aliasToDistrict {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by gen_functional_zones.go; DO NOT EDIT.\n\n")
	b.WriteString("package fuzzutil\n\n")
	b.WriteString("// nationalFunctionalZones 国家级高新区/经开区地址别名 → 规范区县名。\n")
	b.WriteString("var nationalFunctionalZones = map[string]string{\n")
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t%q: %q,\n", k, aliasToDistrict[k]))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("generated %d aliases -> %s\n", len(keys), outPath)
}
